### PR TITLE
Update for Node,js 12.x support

### LINKED ISSUE #546: Does not compile on Node 12.0.0
The requirements to install libxmljs are conflicting and do not allow building on node 12.0.0. 

The install works fine on node 11.x/10.x etc. But when you move to node 12, the following errors result:

```
C:\git\widget-master\server-side>npm install

> libxmljs@0.19.5 install C:\git\widget-master\server-side\node_modules\libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.5 and node@12.0.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v72-win32-x64.tar.gz
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  libxmljs.cc
  xml_attribute.cc
  xml_document.cc
  xml_element.cc
  xml_comment.cc
  xml_namespace.cc
  xml_node.cc
  xml_sax_parser.cc
c:\git\widget-master\server-side\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  C:\Users\kagentes\.node-gyp\12.0.0\include\node\v8.h(2525): note: see declaration of 'v8::Value::ToBoolean' (compiling source file ..\src\libxmljs.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  C:\Users\kagentes\.node-gyp\12.0.0\include\node\v8.h(2563): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\libxmljs.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  C:\Users\kagentes\.node-gyp\12.0.0\include\node\v8.h(2525): note: see declaration of 'v8::Value::ToBoolean' (compiling source file ..\src\xml_attribute.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  C:\Users\kagentes\.node-gyp\12.0.0\include\node\v8.h(2563): note: see declaration of 'v8::Value::BooleanValue' (compiling source file ..\src\xml_attribute.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(105): error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\libxmljs.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(105): error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
  c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\src\xml_attribute.cc)
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': function does not take 1 arguments (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2228: left of '.As' must have class/struct/union (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compiling source file ..\src\libxmljs.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': function does not take 1 arguments (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2228: left of '.As' must have class/struct/union (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
c:\git\widget-master\server-side\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compiling source file ..\src\xml_attribute.cc) [C:\git\widget-master\server-side\node_modules\libxmljs\build\xmljs.vcxproj]
```

### PR DESCRIPTION
**Pull request by tomhughes**
Fixes #546.

### CODE REVIEW

**Comment by atheros** [comment]
Is there a reason this is not being merged?

**Comment by atheros** [comment]
Or is libxmljs dead and I should look for alternatives?

**Comment by vandernorth** [comment]
@rchipka can we get this merged?

**Comment by yacinehmito** [comment]
Is a release planned with this inclusion?

**Pull request merged**
