### PR TITLE
[WIP] add appveyor.yml config for windows build testing

### PR DESCRIPTION
**Pull request by defunctzombie**

### CODE REVIEW

**Comment by gagern** [comment]
Also note the `appveyor.yml` I added in https://github.com/gagern/libxmljs/commit/946a7bedc603b46126f182f8ffe6cb20795d58e5 for #361. I edited my version of it again in https://github.com/gagern/libxmljs/commit/744a48d78ab9a805fbaf4cfd91ef33a7d998a84d to test on more different versions.

**Comment by defunctzombie** [comment]
Thanks for pointing that out, I tried to look over PRs that might have
added that file and missed this. Now I just need to get appveyor connected
to this repo.

**Comment by rchipka** [comment]
#407 adds an AppVeyor configuration and also deploys Windows binaries to GitHub Releases

**Comment by rchipka** [comment]
Fixed by #407

**Pull request closed without merging**
