### PR TITLE
[WIP] V1.0 - RC1

### PR DESCRIPTION
**Pull request by rchipka**
* Backwards compatible API abstractions rewritten in Typescript
 * Auto-generated Typescript definitions
 * Auto-generated bindings (using [SWIG](http://www.swig.org/))
 * Auto-generated documentation
 * Support for multi-threaded parsing
 * Support for NodeJS v12+

Done:

- [x] SWIG wrapper interface for native xmlNode type casts
- [x] SWIG wrapper interface for single and multithreaded memory allocation
- [x] SWIG wrapper interface for reference counting of xmlNodes
- [x] SWIG wrapper interface for multi-threaded API calls
- [x] Script to convert `swig.xml` into Typescript definitions
- [x] XML/HTML Parser API abstractions in Typescript
- [x] XMLDocument API abstractions in Typescript
- [x] XMLNode API abstractions in Typescript
- [x] XMLElement API abstractions in Typescript
- [x] XMLAttribute API abstractions in Typescript
- [x] Tests passing: `main.ts`
- [x] Tests passing `attribute.ts`
- [x] Tests passing `document.ts`
- [x] Tests passing `element.ts`

To-do:

- [x] xmlNs* ref integrity (separate refcounting strategy)
- [x] ensure remaining tests pass
- [x] ensure cross-platform builds on all NodeJS versions

### CODE REVIEW

**Comment by tuananh** [comment]
This is huge. Congrats @rchipka

**Comment by Milo123459** [comment]
Any eta for a merge?

**Comment by rchipka** [comment]
@Milo123459 Currently working past these CI failures

**Comment by totymedli** [comment]
Is there any ETA for this? Maybe an alpha release only for node 14/16? Also, some docs on how to build this on your own would be helpful. According to the CI logs it seems like it works properly in 64bit node 14/16. I would be happy to build it for myself and use it that way.

**Comment by rchipka** [comment]
@totymedli All tests are passing with the exception of a few memory leak tests. We can release once these leaks are resolved and automated builds successfully run on each target OS.

**Comment by rchipka** [comment]
@totymedli Pre-generated SWIG bindings are packed in the repo, so SWIG isn't required to build locally. Running `npm run build` will compile the C++ source code and running `npm run tsc` will compile the typescript source code.

**Comment by rchipka** [comment]
@totymedli you might also need to run `git submodule update --init --recursive`

**Comment by rchipka** [comment]
I don't think we're ready for an alpha release until the tests are all passing.

I'd consider an releasing an alpha version before CI/CD is working, that way we can get more hands on it to experiment cross-platform.

Until then, I highly encourage anyone to pull this branch down and take a look and, if possible, help circle in on this last 20% of work.

**Comment by rchipka** [comment]
Now that we're using Github actions things are looking pretty good.

The last remaining issue is a memory leak that I think has to due with cleaning up namespace references.

I'm considering evaluating the severity of the leak, and, if it's negligible, temporarily bypassing the leak tests so we can cut a release.

I think it's pretty exciting that we'll now have the entire libxml2 API at our disposal in Typescript.

Really looking forward to finally getting this merged in.

**Comment by tuananh** [comment]
super exciting news. is there perf regression? probably not.

**Comment by sbonasu** [comment]
any update on memory leak issue?

**Comment by gonzo09** [comment]
Any info on release date ?

**Comment by DannyNemer** [comment]
Amazing work! I am very excited for this major upgrade!

**Comment by rchipka** [comment]
finish-line

**Comment by rchipka** [comment]
gif

**Comment by tuananh** [comment]
Amazing. Congrats on shipping 1.0 @rchipka I've been a long time user of the project :)

**Pull request merged**
