### PR TITLE
use github action to prebuild + upload assets to github

### PR DESCRIPTION
**Pull request by tuananh**
Fixes: #593 

- i add publish + upload assets step using github actions
- need to create a secret named `NPM_TOKEN`. use npm automation token for this.
- the upload assets step will fail if release is not found so release need to be created prior. my flow is create release and then this will automatically create tag.
- switch to `@mapbox/node-pre-gyp` as the old one already deprecated.

## How i test

i publish as a package under my npm scope, test installing and it works.
 https://www.npmjs.com/package/@tuananh/libxmljs

preview: 

https://github.com/tuananh/libxmljs/actions/runs/2246684658
https://github.com/tuananh/libxmljs/releases/tag/test42

image

Signed-off-by: Tuan Anh Tran <me@tuananh.org>

### CODE REVIEW

**Comment by tuananh** [comment]
@rchipka kindly help me take a look at this

**Comment by tuananh** [comment]
@rchipka i think it's ready for review now. the merge & test file was keep as is. i just add the build + upload assets step.

**Comment by rchipka** [comment]
I added `secrets.NPM_TOKEN`

I'm not sure if I need to do anything for `github.token`

**Comment by rchipka** [comment]
Screen Shot 2022-05-02 at 3 39 26 PM

**Comment by tuananh** [comment]
that's it for me

image

image

**Comment by rchipka** [comment]
Amazing, thank you!!

**Pull request merged**
