### PR TITLE
Fix heap corruption in _wrap_xmlGetNsList

### LINKED ISSUE #649: segmentation fault
Using latest version (1.0.11)

```js
const libXml = require('libxmljs')
const xmlString = `<?xml version="1.0" encoding="UTF-8"?>
<imsx_POXEnvelopeResponse xmlns="http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0">
  <imsx_POXHeader>
    <imsx_POXResponseHeaderInfo>
      <imsx_version>V1.0</imsx_version>
      <imsx_messageIdentifier/>
      <imsx_statusInfo>
        <imsx_codeMajor>success</imsx_codeMajor>
        <imsx_severity>status</imsx_severity>
        <imsx_description/>
        <imsx_messageRefIdentifier>ff119fad-1bdd-41af-b908-e7665abc4b28</imsx_messageRefIdentifier>
        <imsx_operationRefIdentifier>replaceResult</imsx_operationRefIdentifier>
        
      </imsx_statusInfo>
    </imsx_POXResponseHeaderInfo>
  </imsx_POXHeader>
  <imsx_POXBody><replaceResultResponse/></imsx_POXBody>
</imsx_POXEnvelopeResponse>`

const xml = libXml.parseXml(xmlString)

xml.namespaces()
```

Causes node to exit with a segmentation fault, however adding in a `xml.root()` before the `xml.namespaces()` fixes the issue (I think!).
It's not 100% reproducible, but I could do it 8 out of 10 times (just by pasting in the above into the node REPL).

### PR DESCRIPTION
**Pull request by shunkica**
Fixes #649

### CODE REVIEW

**Comment by rchipka** [comment]
libxml2.cc is autogenerated by SWIG

you'll need to define this override in the SWIG source files instead

**Comment by shunkica** [comment]
> libxml2.cc is autogenerated by SWIG
> 
> you'll need to define this override in the SWIG source files instead

Ok I will look into it. I have no experience with SWIG.

**Comment by shunkica** [comment]
@rchipka I hope it is ok now.

**Comment by shunkica** [comment]
Does `swig.xml` need to be a part of the repository?

**Pull request closed without merging**
