### PR TITLE
Use AppVeyor configuration from libxmljs-mt

### PR DESCRIPTION
**Pull request by gagern**
You may want to use this instead of #382, since the file here is tested in practice in my fork. Originally a previous version of this file was part of #361 which you wanted split up.

### CODE REVIEW

**Comment by defunctzombie** [comment]
I am all for adding AppVeyor, I've just been waiting on @polotek to setup the hooks cause I am not an admin on this repo.

**Comment by gagern** [comment]
This may be superseded by #407. Comparing with that, this one here

* does not do deployment
* does not test against node prior to version 4
* does test against latest Node versions Stable and LTS, which at some point may be beyond 4 and 5
* does test against Visual Studio 2013 which was important due to different `snprintf` handling (see gagern@7e82427a851d0aae12b0ca39c70f088e717798b7 and gagern@744a48d78ab9a805fbaf4cfd91ef33a7d998a84d) but probably not as important if you do binary releases
* initializes git submodules, which aren't used in the master branch

**Comment by rchipka** [comment]
@gagern Are your AppVeyor tests all passing on libxmljs 0.17.1? When AppVeyor runs the tests in my PR there is some unexpected behavior, so if yours is passing then maybe we should merge this config for 0.17.2 until the test issues are sorted out.

**Comment by rchipka** [comment]
So, @gagern's config [builds successfully](https://ci.appveyor.com/project/rchipka/libxmljs-5pd5d) even on 0.17.1. I'm really not sure what's causing the weird results on my build tests.

**Comment by rchipka** [comment]
Fixed by #407

**Pull request closed without merging**
