### PR TITLE
Build for Node 9 and Node 10

### PR DESCRIPTION
**Pull request by pietermees**

### CODE REVIEW

**Comment by pietermees** [comment]
I also wonder whether Node 0.10 and 0.12 should be deprecated.

**Comment by tamtamchik** [comment]
Having the same issues.

**Comment by rchipka** [comment]
@pietermees Between this or #507, I'll except a PR that skips the test, but only if it just skips for the problematic NodeJS version and prints a big warning for future reference. 

This will be good enough for now so that people can still get binaries. We'll sort out any memory issues in the future.

**Comment by rchipka** [comment]
Fixed by #508

**Pull request closed without merging**
