### PR TITLE
Refactor element/text base class

### PR DESCRIPTION
**Pull request by teleological**
Factored out common methods in Element/Text. ~~Couldn't come up with a decent name for the result; would welcome suggestions.~~

~~Perhaps more importantly: Noticed some memory issues when adding text siblings. It may be good to patch those before letting this out into the wild. Working on a fix, but wanted to get a clean refactor out first.~~ ( Bug fixes in #362 )

### CODE REVIEW

**Comment by teleological** [comment]
Added a fix for when text nodes are added as children to nodes whose final children are also text nodes. Fixes are needed for adding next and previous siblings as well.

**Comment by teleological** [comment]
Added fix and tests for adding merged text sibilings. All merged text tests segfault without this PR.

**Comment by teleological** [comment]
Renamed "fraternal" nodes to "non-attribute nodes", updated XmlComment to be a subclass, and changed XmlNode::New so that it creates the correct kind of subclasses (fixes #226)

**Comment by rc0x03** [comment]
It could also be called a proto-element type. Also, in #360 the `add_child`, `add_next_sibling`, `add_prev_sibling`, and `import_element` functions have all been moved to `XmlNode`. The reason I moved these to XmlNode is so that the refcount logic is all in one location. This way, anything that inherits from XmlNode will have these functions available, but won't have them exposed via the API unless the XmlNode inheritor implements `addChild()`, etc.

**Comment by teleological** [comment]
@rc0x03 I also moved `import_element` to `XmlNode`, but didn't move the others because they didn't seem a good fit with `XmlAttribute`, which also descends from node. Have you looked into that? I've started to review #360.

**Comment by teleological** [comment]
I'm going to extract the memory fix for adding/merging text nodes into a separate PR that can be merged without delay. I will leave the refactoring of the Element/Text base class for later consideration. The correction of the wrapper selection for child nodes, etc. is technically a bug fix, but it also impacts usage, since nodes returned from some operations won't respond to the same API as before the change. So it would be kinder not to shoehorn it into a minor release.

**Comment by teleological** [comment]
Bug fixes extracted to #359

**Pull request closed without merging**
