### PR TITLE
Bugfix/640

### LINKED ISSUE #640: nextSibling/prevSibling always returns XMLNode
The following methods always return an XMLNode: 

- `nextSibling`
- `prevSibling`
- `prevElement`
- `nextElement`

The reason for this is that the prevSibling and nextSibling methods call the `createXMLReference` method and not `refToNodeType`:
https://github.com/libxmljs/libxmljs/blob/3121013c0e447d267bf4514317c52ad81670f2f5/lib/node.ts#L433 
https://github.com/libxmljs/libxmljs/blob/3121013c0e447d267bf4514317c52ad81670f2f5/lib/node.ts#L437

### PR DESCRIPTION
**Pull request by kpalatzky**
Fixes #640

### CODE REVIEW

**Comment by kpalatzky** [comment]
@rchipka The pipeline fails due to a GYP error. I cannot fix this error myself.

**Comment by rchipka** [comment]
We shouldn't use refToNodeType because then we have to use a type assertion.

Instead we should check if the `.prev` ref is null and return null, otherwise return `createXMLReference(XMLNode,...)`, that way the return type will be inferred correctly.

**Comment by rchipka** [comment]
Also if you could add a test for this that would be greatly appreciated

**Comment by rchipka** [comment]
Hmm, although that does raise the question of how to handle casting to XMLElement in nextElement/prevElement

**Comment by kpalatzky** [comment]
It also seems that the build on ubuntu does work fine. Whats reason why it does fail on macos? I am not familiar with GYP errors.

**Comment by rchipka** [comment]
Seems like maybe a python version issue considering the error is related to unknown flags for an `open()` call

**Comment by rchipka** [comment]
I agree that we should always return an instance that best matches the underlying node ref type, however I'm wondering if there's a way we can do this without a manual type assertion

**Pull request closed without merging**
